<?php
require_once "PHP/Object.php";

class PHP_Object_Resource extends PHP_Object
{
    public $argOffsets =  array(
        'fprintf' => 0,
        'mysql_affected_rows' => 0,
        'mysql_change_user' => 3,
        'mysql_client_encoding' => 0,
        'mysql_close' => 0,
        'mysql_create_db' => 1,
        'mysql_data_seek' => 0,
        'mysql_db_name' => 0,
        'mysql_db_query' => 2,
        'mysql_drop_db' => 1,
        'mysql_errno' => 0,
        'mysql_error' => 0,
        'mysql_fetch_array' => 0,
        'mysql_fetch_assoc' => 0,
        'mysql_fetch_field' => 0,
        'mysql_fetch_lengths' => 0,
        'mysql_fetch_object' => 0,
        'mysql_fetch_row' => 0,
        'mysql_fetch_flags' => 0,
        'mysql_field_len' => 0,
        'mysql_field_name' => 0,
        'mysql_field_seek' => 0,
        'mysql_field_table' => 0,
        'mysql_field_type' => 0,
        'mysql_free_result' => 0,
        'mysql_get_host_info' => 0,
        'mysql_get_proto_info' => 0,
        'mysql_get_server_info' => 0,
        'mysql_info' => 0,
        'mysql_insert_id' => 0,
        'mysql_list_dbs' => 0,
        'mysql_list_fields' => 2,
        'mysql_list_process' => 0,
        'mysql_list_tables' => 1,
        'mysql_num_fields' => 0,
        'mysql_num_rows' => 0,
        'mysql_ping' => 0,
        'mysql_query' => 1,
        'mysql_real_escape_string' => 1,
        'mysql_result' => 0,
        'mysql_select_db' => 1,
        'mysql_set_charset' => 1,
        'mysql_stat' => 0,
        'mysql_tablename' => 0,
        'mysql_thread_id' => 0,
        'mysql_unbuffered_query' => 1,
        'pg_affected_rows' => 0,
        'pg_cancel_query' => 0,
        'pg_client_encoding' => 0,
        'pg_close' => 0,
        'pg_connect_busy' => 0,
        'pg_connect_reset' => 0,
        'pg_connect_status' => 0,
        'pg_convert' => 0,
        'pg_copy_from' => 0,
        'pg_copy_to' => 0,
        'pg_dbname' => 0,
        'vfprintf' => 0,
    );

}
