<?php
require_once 'PHPUnit/Framework.php';

require_once '../../src/Net/Pocketbell.php';

/**
 * Test class for Pocketbell.
 * Generated by PHPUnit on 2009-04-21 at 20:57:55.
 */
class PocketbellTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Pocketbell
     * @access protected
     */
    protected $object;


    protected $className;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        //$this->object = new Pocketbell;
        $this->className = "Net_Pocketbell";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }


    public function testConstructor()
    {

        $this->assertClassHasAttribute('def', $this->className);


        //
        $class = new $this->className();

        $this->assertNotNull($class->def);
    }


    /**
     * @todo Implement testNum2kana().
     */
    public function testNum2kana() {

        

        //$this->assertEquals
        $ntt = new $this->className('NTT');

        $this->assertEquals('＆',$ntt->num2kana('08'));


        $tm = new $this->className('TM');
        $this->assertEquals('８', $tm->num2kana('08'));


        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testKana2num().
     */
    public function testKana2num() {

        $ntt = new $this->className('NTT');
        $this->assertEquals('08',$ntt->kana2num('＆'));
        
        $tm = new $this->className('TM');
        $this->assertEquals('08', $tm->kana2num('８'));


        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetDefinitionNtt().
     */
    public function testSetDefinitionNtt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetDefinitionTm().
     */
    public function testSetDefinitionTm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
