<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Http/Response/CharactorEncoding/Wrapper/Zf.php';

/**
 * Test class for Diggin_Http_Response_CharactorEncoding_Wrapper_Zf.
 * Generated by PHPUnit on 2009-10-03 at 20:37:07.
 */
class Diggin_Http_Response_CharactorEncoding_Wrapper_ZfTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Http_Response_CharactorEncoding_Wrapper_Zf
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Http_Response_CharactorEncoding_Wrapper_Zf;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreateWrapper().
     */
    public function testCreateWrapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetBody().
     */
    public function testGetBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetEncodingFrom().
     */
    public function testSetEncodingFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetEncodingFrom().
     */
    public function testGetEncodingFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetEncodingTo().
     */
    public function testSetEncodingTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetEncodingTo().
     */
    public function testGetEncodingTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
