propel:
  _attributes: { package: plugins.opFreepagePlugin.lib.model }
  freepage:
    id: ~
    title:      { type: longvarchar }
    body:       { type: longvarchar }
    app_type:   { type: varchar(16), required: true, default: 'pc'}
    auth:       { type: tinyint, required: true, default: 1}
    created_at: ~
    updated_at: ~