<?xml version="1.0"?>
<refentry id="{@id}">
    <refnamediv>
        <refname>Approaches with Client</refname>
        <refpurpose>Description of the various approaches in using the Client class</refpurpose>
    </refnamediv>
    <refsynopsisdiv>
        <author>Vasil Rangelov
            <authorblurb>
                {@link mailto:boen.robot@gmail.com boen.robot@gmail.com}
            </authorblurb>
        </author>
    </refsynopsisdiv>
    {@toc}
    <refsect1 id="{@id sync-request}">
        <title>Synchonized requests</title>
        <para>
The easiest approach in using Net_RouterOS is to connect, send a request, and either stop there or analyze the response if you need to.
        </para>
    </refsect1>
</refentry>