<?php
require_once 'PHP/Object/Numeric.php';

class PHP_Object_Numeric_Integer extends PHP_Object_Numeric
{

    protected $aliasMethods = array();

    public $argOffsets =  array(
        'array_change_key_case' => 1,
        'array_chunk' => 1,
        'array_fill' => 0,
        'array_pad' => 1,
        'array_rand' => 1,
        'array_reduce' => 2,
        'array_slice' => 1,
        'array_splice' => 1,
        'arsort' => 1,
        'assert_options' => 0,
        'asort' => 1,
        'chunk_split' => 1,
        'count_chars' => 1,
        'count' => 1,
        'date_sun_info' => 0,
        'date' => 1,
        'error_log' => 1,
        'error_reporting' => 1,
        'explode' => 2,
        'extract' => 1,
        'get_html_translation_table' => 0,
        'getdate' => 0,
        'getrusage' => 0,
        'gmdate' => 1,
        'gmstrftime' => 1,
        'hebrev' => 1,
        'hebrevc' => 1,
        'html_entity_decode' => 1,
        'htmlentities' => 1,
        'htmlspecialchars_decode' => 1,
        'htmlspecialchars' => 1,
        'idate' => 1,
        'krsort' => 1,
        'ksort' => 1,
        'localtime' => 0,
        'metaphone' => 1,
        'mysql_connect' => 4,
        'mysql_data_seek' => 1,
        'mysql_db_name' => 1,
        'mysql_fetch_array' => 1,
        'mysql_fetch_field' => 1,
        'mysql_fetch_flags' => 1,
        'mysql_field_len' => 1,
        'mysql_field_name' => 1,
        'mysql_field_seek' => 1,
        'mysql_field_table' => 1,
        'mysql_field_type' => 1,
        'mysql_pconnect' => 3,
        'mysql_result' => 1,
        'mysql_tablename' => 1,
        'nl_langinfo' => 0,
        'ob_gzhandler' => 1,
        'ob_implicit_flush' => 0,
        'ob_start' => 1,
        'pg_connect' => 1,
        'pg_convert' => 3,
        'phpcredits' => 0,
        'phpinfo' => 0,
        'rsort' => 1,
        'set_error_handler' => 1,
        'setlocale' => 0,
        'sizeof' => 1,
        'sort' => 1,
        'str_pad' => 1,
        'str_repeat' => 1,
        'str_split' => 1,
        'str_word_count' => 1,
        'strcspn' => 2,
        'stripos' => 2,
        'strftime' => 1,
        'strncasecmp' => 2,
        'strncmp' => 2,
        'strpos' => 2,
        'strripos' => 2,
        'strrpos' => 2,
        'strspn' => 2,
        'strtotime' => 1,
        'substr_compare' => 2,
        'substr_count' => 2,
        'substr_replace' => 2,
        'substr' => 1,
        'timezone_identifiers_list' => 0,
        'trigger_error' => 1,
        'user_error' => 1,
        'wordwrap' => 1,
    );

}
